#!/usr/bin/env bash

active_space (){
	WORKSPACE_WINDOWS=$(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id')
	echo $WORKSPACE_WINDOWS
}

active_space
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    active_space
done