#!/usr/bin/env bash

# shellcheck disable=SC2034
AUDIO_FIELD="SentenceAudio"
SCREENSHOT_FIELD="Picture"
SENTENCE_FIELD="Sentence"
# leave OUTPUT_MONITOR blank to autoselect a monitor.
OUTPUT_MONITOR=""
AUDIO_BITRATE="256k"
AUDIO_FORMAT="mp3"
AUDIO_VOLUME="1"
IMAGE_FORMAT="webp"
# -2 to calculate dimension while preserving aspect ratio.
IMAGE_WIDTH="-2"
IMAGE_HEIGHT="300"

# Wayland stuffs
get_selection() {
    # get a region of the screen for future screenshotting.
    slurp
}

take_screenshot_region() {
    # function to take a screenshot of a given screen region.
    # $1 is the geometry of the region from get_selection().
    # $2 is the output file name.
    local -r geom="$1"
    local -r path="$2"
    grim -g "$geom" "$path"
}

take_screenshot_window() {
    # function to take a screenshot of the current window.
    # $1 is the output file name.
    local -r path="$1"
    hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - "$path"
}

copied_text() {
    # get the contents of the clipboard.
    wl-paste
}